# Generated by Django 4.2 on 2025-02-21 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mvt', '0002_alter_cripto_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'USD - Dólar estadounidense'), ('EUR', 'EUR - Euro'), ('BTC', 'BTC - Bitcoin'), ('JPY', 'JPY - Yen japonés'), ('GBP', 'GBP - Libra esterlina'), ('AUD', 'AUD - Dólar australiano'), ('CAD', 'CAD - Dólar canadiense'), ('CHF', 'CHF - Franco suizo'), ('CNH', 'CNH - Yuan chino')], default='USD', max_length=3)),
                ('country', models.CharField(blank=True, choices=[('ES', 'España'), ('FR', 'Francia'), ('DE', 'Alemania'), ('IT', 'Italia'), ('NL', 'Países Bajos'), ('BE', 'Bélgica'), ('PT', 'Portugal'), ('SE', 'Suecia'), ('AT', 'Austria'), ('FI', 'Finlandia'), ('DK', 'Dinamarca'), ('PL', 'Polonia'), ('IE', 'Irlanda'), ('GR', 'Grecia'), ('CZ', 'República Checa'), ('HU', 'Hungría'), ('SK', 'Eslovaquia'), ('RO', 'Rumanía')], max_length=2)),
                ('receive_alerts', models.BooleanField(default=False)),
                ('alert_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
